apiVersion: v1 
kind: Pod  
metadata: 
 name: nginx 
spec:
 containers: 
 - name: animals 
   image: supergiantkir/animals:bear
   ports: 
   - containerPort: 80
   volumeMounts:
    - name: app-storage
      mountPath: /storage/nginx
 - name: springapp
   image: yanivomc/spring-music:latest
   ports: 
   - containerPort: 8080
   volumeMounts:
    - name: app-storage
      mountPath: /storage/data


 volumes:
 - name: app-storage
   emptyDir: {}
